# Generated by Django 5.2.1 on 2025-06-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_remove_userprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='出生日期'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fitness_level',
            field=models.CharField(blank=True, max_length=50, verbose_name='健身程度'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='身高 (公分)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='體重 (公斤)'),
        ),
    ]
